### ISSUE TITLE
AppDaemon parse_datetime() broken in version 0.17.11, worked until 0.17.10

### ISSUE THREAD

**Issue by ManniTom** [home-assistant/appdaemon#2474]
### What happened?

(0.17.11 is the version that the Home Assistant AppDaemon Addon is showing) 

when variable s1 has the content: 2025-10-25 13:51:42
the following line:
ls_unaware = self.parse_datetime(s1, aware=False)
will create an exception

the same code worked for many years, up to 0.17.10. With 0.17.11 it's broken
i use HASS 2025.10.3 with the AppDaemon AddOn.
i don't know if it is important, but 2025-10-25 was the last day of DST over here.

### Version

?

### Installation type

Home Assistant add-on

### Relevant log output

```sh

```

### Relevant code in the app or config file that caused the issue

```sh

```

**Comment by jsl12** [comment]
This is already fixed, but hasn't quite made it to the add-on yet

**Comment by ManniTom** [comment]
in the home Assistant updates, i see AppDaemon AddOn v0.17.12.
Is it fixed there?

**Comment by ManniTom** [comment]
Fom todays test: The issue is still present in the actual AppDaemon HA AddOn version 0.17.12.

**Comment by ManniTom** [comment]
Fom todays NEW test: The issue is still present in the actual AppDaemon HA AddOn version 0.17.13.
