### ISSUE TITLE
listen_state with oneshot=True throws exception.

### ISSUE THREAD

**Issue by Swamp-Ig** [home-assistant/appdaemon#353]
Doing a listen_state with the oneshot=True flag throws an exception when it triggers.

It happens [here](https://github.com/home-assistant/appdaemon/blob/dev/appdaemon/appdaemon.py#L2314)  because there's no "handle" set in kwargs.

I did try attaching a debugger but I couldn't get it to work, but looking at the code it should be [set here](https://github.com/home-assistant/appdaemon/blob/dev/appdaemon/appdaemon.py#L2185) but isn't for some reason.

(I'm not really a python coder)

**Comment by Swamp-Ig** [comment]
Yeh it's a bug for sure.

Have made a test case to demonstrate and updated the links to point to the right place.

Test case and log attached. 

[testapp.py.txt](https://github.com/home-assistant/appdaemon/files/2265616/testapp.py.txt)
[appdaemon_issue.log](https://github.com/home-assistant/appdaemon/files/2265613/appdaemon_issue.log)

**Comment by Swamp-Ig** [comment]
Here's another test app demonstrating the issue.

In this version I've only registered one listener.

Note the comments in the log file

[testapp2.py.txt](https://github.com/home-assistant/appdaemon/files/2265687/testapp2.py.txt)
[appdaemon_issue2.log](https://github.com/home-assistant/appdaemon/files/2265688/appdaemon_issue2.log)

**Comment by acockburn** [comment]
OK, thanks for flagging it - I'll get this into the next release.

**Comment by acockburn** [comment]
I tested and couldn't reproduce this - it's possible I fixed it already in the latest version. Can you retest with version 3.0.2 when I release it please?

**Comment by ConnorGriffin** [comment]
I just did some tests with the docker images tagged 'latest' and 'dev'. This still appears to be broken, though the behavior is a little bit different now. It seems like if you have multiple oneshots, the first to trigger will cancel all the others. And if you if you have a oneshot that's monitoring an entity for a certain state (new = on) and change to a non-monitored state (new = off) before ever changed the state to on, the oneshot will still get cancelled. 

I don't think I did a very good job at explaining this, but it should be easily duplicated. 

I used two input_booleans with assorted listen_state calls to a callback that just logs the old and new state. My test app looks something like this, with changes to the listen_states depending on the test scenario. 
```
import appdaemon.plugins.hass.hassapi as hass

class Test(hass.Hass):

    def initialize(self):
        self.listen_state(
            self.state_log,
            entity = 'input_boolean.test_switch',
            new = 'on',
            oneshot = True
        )

        self.listen_state(
            self.state_log,
            entity = 'input_boolean.test_switch',
            new = 'off',
            oneshot = True
        )

    def state_log(self, entity, attribute, old, new, kwargs):
        self.log('{}/{}: {} -> {}'.format(entity, attribute, old, new))
```

### Docker:latest (3.0.1) 

1. Single listen_state, oneshot: Works as expected
2. Two listen_states, both oneshots, one listening for new='off' and one listening for new='on': Getting the **KeyError: 'handle'** error sometimes. Most times only the first triggered oneshot works. So if I reload with my input_boolean set to off, then turn it on and off again, only the new='on' listen_state is triggered. 
3. Same as test 2 except I am listening for the same state (new='on') for two different input_booleans: Consistently getting the **KeyError: 'handle'** error when toggling the state of the input_boolean in the first listen_state. The switch tied to the second listen_state doesn't seem to do anything.
4. Same as test 3 except listening for different states instead of the same states: Same result as test 3. 


### Docker:dev
1. Single listen_state, oneshot: Does nothing if the state changes to a state that is **not** being listened for. For example, if I listen for 'on' and the state changes from 'on' to 'off' and then back to 'on', nothing happens.
2. Two listen_states, both oneshots, one listening for new='off' and one listening for new='on': Only the first triggered oneshot works. So if I reload with my input_boolean set to off, then turn it on and off again, only the new='on' listen_state is triggered. 
3. Same as test 2 except I am listening for the same state (new='on') for two different input_booleans: Mix of results from test 1 and 2. If switch1 is listening for new='on' and switch2 is listening for new='off' and I turn off switch1, none of the listen_states will get fired. If the first thing I do is trigger a state that I am listening for, that specific listen_state will fire, but the other will do nothing.
4. Same as test 3 except listening for different states instead of the same states: Same result as test 3.

**Comment by acockburn** [comment]
3.0.2 is out now - is this still an issue for you?

**Comment by ConnorGriffin** [comment]
I am getting very similar results.

Here is a video where I performed my tests: https://gfycat.com/FriendlyCaringBushbaby

1. Single listen_state with oneshot listening for new=on: 
    a. Starting in the off position:  Works
    b. Starting in the on position: Doesn't work
2. Two listen_states with oneshots listening for different values:
    a. Starting opposite what we're listening for: Only the first triggered fires
    b. Starting at what we're listening for: None trigger
    c. Starting in the same position (both off): Only the first triggers (doesn't trigger after turning switch 2 on then off)
3. Two listen_states with oneshots listening for new=on:
    a. Starting in the off position: Only the first triggered fires
    b. Starting in the on position: Doesn't work

**Comment by acockburn** [comment]
Hi there - so, thanks to your thorough testing and nice video, I identified a flaw in Oneshot - it was never working right, before, it must have been a Friday afternoon when I implemented it ;) It should be all fixed now in the dev version and in the next release.
