### ISSUE TITLE
SSL connection with websockets fails

### ISSUE THREAD

**Issue by FireFrei** [home-assistant/appdaemon#81]
HASS version: 0.48.1
AppDaemon version: 2.0.3

I'm still trying to setup AppDaemon to talk to HASS via a SSL secured connection. 
```
2017-07-11 11:42:11.677833 INFO AppDaemon Version 2.0.3 starting
2017-07-11 11:42:11.679021 INFO Configuration read from: /conf/appdaemon.yaml
2017-07-11 11:42:12.810067 INFO Got initial state
2017-07-11 11:42:12.823698 INFO App initialization complete
2017-07-11 11:42:12.835773 INFO Starting dashboard
2017-07-11 11:42:13.129218 WARNING Disconnected from Home Assistant, retrying in 5 seconds
```

I'm using the docker image and have trusted my CA that signed the HASS certificate
`docker run -d --name "hass-appdaemon" (...) -v /etc/localtime:/etc/localtime:ro -v /etc/ssl/certs:/etc/ssl/certs:ro -e "SSL_CERT_DIR=/etc/ssl/certs" -e "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt" -e "REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt" hass-appdaemon:latest`

My AppDaemon config is:
```
  cert_path: '/etc/ssl/certs/ca-certificates.crt'
  cert_verify: False
```

If I try to execute appdaemon within the conatiner in DEBUG mode, I receive the following warning:
```
2017-07-11 11:47:39.319567 WARNING Disconnected from Home Assistant, retrying in 5 seconds
2017-07-11 11:47:39.326428 WARNING ------------------------------------------------------------
2017-07-11 11:47:39.334239 WARNING Unexpected error:
2017-07-11 11:47:39.340846 WARNING ------------------------------------------------------------
2017-07-11 11:47:39.349033 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1332, in appdaemon_loop
    "{}/api/websocket".format(url), sslopt=sslopt
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 487, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 211, in connect
    options.pop('socket', None))
  File "/usr/local/lib/python3.6/site-packages/websocket/_http.py", line 77, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/usr/local/lib/python3.6/site-packages/websocket/_http.py", line 182, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/usr/local/lib/python3.6/site-packages/websocket/_http.py", line 160, in _wrap_sni_socket
    server_hostname=hostname,
  File "/usr/local/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

2017-07-11 11:47:39.354916 WARNING ------------------------------------------------------------
```

If I change the Dockerfile and start Appdaemon with --commtype=SSE it works perfectly.

**Comment by FireFrei** [comment]
Testing the SSL connection with openssl from the container:
`root@86dea735d5d3:/usr/src/app# openssl s_client -connect hass.local:8123`


```
(...)
    Start Time: 1499767300
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
```

So my certificates actually seem to work :-)

**Comment by acockburn** [comment]
Can your post your full AppDaemon.yaml file please

**Comment by FireFrei** [comment]
Sure :-)

```
HASS:
  ha_url: 'https://hass.home.local:8123'
  ha_key: 'XYZ'

AppDaemon:
  logfile: STDOUT
  errorfile: STDERR
  threads: 10
  app_dir: '/conf/apps'
  cert_path: '/etc/ssl/certs/ca-certificates.crt'
  cert_verify: False

HADashboard:
  dash_url: 'http://hass-dashboard.home.local:5050'
  dash_dir: '/conf/dashboards'
```

**Comment by acockburn** [comment]
OK, so a problem in the Web socket code for self signed certs. BTW, you can add `--commtype SSE` in the extra args, no need to change the Dockerfile itself.

**Comment by acockburn** [comment]
I just merged a PR that may fix this - can you test against the next version please? (or the current dev branch if you are feeling adventurous)

**Comment by FireFrei** [comment]
Pulled dev branch and created docker image. I still have the same issues.
cert_verify is set to false. openssl s_client -connect says certificate is valid.

```
2017-07-15 10:40:57.312720 INFO AppDaemon Version 2.0.4 starting
2017-07-15 10:40:57.314948 INFO Configuration read from: /conf/appdaemon.yaml
2017-07-15 10:40:57.316339 DEBUG get_ha_config()
2017-07-15 10:40:57.996922 DEBUG Entering run()
2017-07-15 10:40:58.109795 DEBUG Creating worker threads ...
2017-07-15 10:40:58.113955 DEBUG Done
(...)
2017-07-15 10:41:03.850154 INFO Disconnecting from Home Assistant
2017-07-15 10:41:03.856268 DEBUG Refreshing HA state
2017-07-15 10:41:03.866676 DEBUG get_ha_state: entity is None
2017-07-15 10:41:04.239639 INFO Got initial state
2017-07-15 10:41:04.245916 INFO App initialization complete
2017-07-15 10:41:04.493135 WARNING Disconnected from Home Assistant, retrying in 5 seconds
2017-07-15 10:41:04.495092 WARNING ------------------------------------------------------------
2017-07-15 10:41:04.497229 WARNING Unexpected error:
2017-07-15 10:41:04.499014 WARNING ------------------------------------------------------------
2017-07-15 10:41:04.506035 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1336, in appdaemon_loop
    "{}/api/websocket".format(url), sslopt=sslopt
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 487, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 211, in connect
    options.pop('socket', None))
  File "/usr/local/lib/python3.6/site-packages/websocket/_http.py", line 77, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/usr/local/lib/python3.6/site-packages/websocket/_http.py", line 182, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/usr/local/lib/python3.6/site-packages/websocket/_http.py", line 160, in _wrap_sni_socket
    server_hostname=hostname,
  File "/usr/local/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

2017-07-15 10:41:04.509604 WARNING ------------------------------------------------------------
```

**Comment by acockburn** [comment]
OK, I'll have to try and reproduce this.

**Comment by cgarwood** [comment]
Possibly related? I'm getting the same errors with a valid wildcard certificate.  ha_url points to a domain that matches the certificate. --commtype SSE works OK, just seems to be a websocket problem

**Comment by martenjacobs** [comment]
I'm having a very similar issue. My HASS install is using a correctly signed certificate, but I would prefer to have AppDaemon not validate the certificate, as it's running on the same machine, and connecting to 127.0.0.1 is a bit more convenient. I'm using AppDaemon 2.1.12. Connecting to HASS using the remote url (for which the certificate is valid) works fine, but when using 127.0.0.1 and setting 'cert_verify' to False, I get the following exception:

```python
2017-12-18 19:58:12.010442 WARNING Disconnected from Home Assistant, retrying in 5 seconds
2017-12-18 19:58:12.010705 WARNING ------------------------------------------------------------
2017-12-18 19:58:12.010876 WARNING Unexpected error:
2017-12-18 19:58:12.011027 WARNING ------------------------------------------------------------
2017-12-18 19:58:12.012912 WARNING Traceback (most recent call last):
  File "/home/srv/homeassistant/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 1208, in appdaemon_loop
    "{}/api/websocket".format(url), sslopt=sslopt
  File "/home/srv/homeassistant/lib/python3.5/site-packages/websocket/_core.py", line 487, in create_connection
    websock.connect(url, **options)
  File "/home/srv/homeassistant/lib/python3.5/site-packages/websocket/_core.py", line 211, in connect
    options.pop('socket', None))
  File "/home/srv/homeassistant/lib/python3.5/site-packages/websocket/_http.py", line 77, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/srv/homeassistant/lib/python3.5/site-packages/websocket/_http.py", line 182, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/srv/homeassistant/lib/python3.5/site-packages/websocket/_http.py", line 160, in _wrap_sni_socket
    server_hostname=hostname,
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 638, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 297, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname '127.0.0.1' doesn't match either of '*.example.com', 'example.com'
```
_(I changed the URL to example.com)_

**Comment by acockburn** [comment]
There have been some changes in this area for the upcoming AppDaemon 3.0 please retest when you get a chance after the release

**Comment by acockburn** [comment]
There have been some changes in hass.io just about to be merged that fixed one issue with WS - this might have been the cause in some cases. Also, I have changed some of the code around in AppDaemon 3.0 beta 2 - would you be able to retest for me please?

**Comment by acockburn** [comment]
I just tested this on the latest beta with a self signed cert and all was well. Closing now, but happy to reopen if you see the problem with 3.0 code.

**Comment by FireFrei** [comment]
Hi, 
sorry, I hadn't had the time to test it.
I have tested it now with the newest version 3.0.0b5 and HASS 0.64.3
self.get_state() works now without any problems.

When setting/updating a state (with self.set_state() or self.call_service()) I still receive the following error:

```
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='hass.home.local', port=8123): Max retries exceeded with url: /api/services/input_number/set_value (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)'),))
```

My AppDaemon config is:
```
appdaemon:
  threads: 10
  app_dir: '/srv/apps'
  plugins:
    HASS:
      type: hass
      ha_url: 'https://hass.home.local:8123'
      ha_key: 'ABC'
      cert_path: '/etc/ssl/certs/ca-certificates.crt'
      cert_verify: False
```


Setting a state with curl works without any problem.
`curl -X POST -H "x-ha-access: ABC" -H "Content-Type: application/json" -d '{"attributes": {"friendly_name": "Volume", "icon": "mdi:volume-medium", "max": -20.0, "min": -100.0, "mode": "slider", "step": 0.5}, "entity_id": "input_number.volume", "state": "-30.0"}' "https://hass.home.local:8123/api/states/input_number.volume"`
